CampfireButler/config/routes.rb
Rails.application.routes.draw do
  resources :meal_items

  get 'generate/index'

  get 'generate/createmeal'

  get 'generate/showmeal'

  get 'generate/editmeal'

  get 'generate/index'

  get 'generate/customise'

  get 'generate/index'

  root 'generate#index'

end

CampfireButler/app/models/generate.rb
class Generate < ActiveRecord::Base
end

CampfireButler/app/models/meal_item.rb
class MealItem < ActiveRecord::Base
    def self.up
        create_table :meal_item do |t|
            t.string :title
            t.decimal :num_serves, :scale => 2
            t.decimal :size_serve
            t.text :comments
            t.timestamps
        end
    end
    
    def self.down
        drop_table :meal_item
    end
end

CampfireButler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CampfireButler/app/controllers/generate_controller.rb
class GenerateController < ApplicationController
  def index

  end

  def customise

  end

 
end

CampfireButler/app/controllers/meal_items_controller.rb
class MealItemsController < ApplicationController
  before_action :set_meal_item, only: [:show, :edit, :update, :destroy]

  # GET /meal_items
  # GET /meal_items.json
  def index
    @meal_items = MealItem.all
  end

  # GET /meal_items/1
  # GET /meal_items/1.json
  def show
  end

  # GET /meal_items/new
  def new
    @meal_item = MealItem.new
  end

  # GET /meal_items/1/edit
  def edit
  end

  # POST /meal_items
  # POST /meal_items.json
  def create
    @meal_item = MealItem.new(meal_item_params)

    respond_to do |format|
      if @meal_item.save
        format.html { redirect_to @meal_item, notice: 'Meal item was successfully created.' }
        format.json { render :show, status: :created, location: @meal_item }
      else
        format.html { render :new }
        format.json { render json: @meal_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_items/1
  # PATCH/PUT /meal_items/1.json
  def update
    respond_to do |format|
      if @meal_item.update(meal_item_params)
        format.html { redirect_to @meal_item, notice: 'Meal item was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_item }
      else
        format.html { render :edit }
        format.json { render json: @meal_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_items/1
  # DELETE /meal_items/1.json
  def destroy
    @meal_item.destroy
    respond_to do |format|
      format.html { redirect_to meal_items_url, notice: 'Meal item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_item
      @meal_item = MealItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_item_params
      params.require(:meal_item).permit(: title, :num-serves, :size-serve, :comments)
    end
end

CampfireButler/app/helpers/application_helper.rb
module ApplicationHelper
end

CampfireButler/app/helpers/generate_helper.rb
module GenerateHelper
end

CampfireButler/app/helpers/meal_items_helper.rb
module MealItemsHelper
end

CampfireButler/app/views/generate/_form.html.erb
<%= form_for(@generate) do |f| %>
  <% if @generate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generate.errors.count, "error") %> prohibited this camp generation from being saved:</h2>

      <ul>
      <% @generate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_area :number %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br>
    <%= f.file_field :starttime %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br>
    <%= f.file_field :endtime %>
  </div>
  <div class="field">
    <%= f.label :allergies %><br>
    <%= f.file_field :allergies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CampfireButler/app/views/generate/customise.html.erb
<div class="navbar">
</div>
<h1>Customise Camp</h1>
<p> The Menu is in your Hands </p>
<p> Default Menu <%= link_to "Default", generate_index_path %>!</p>

CampfireButler/app/views/generate/index.html.erb
<div class="navbar">
	<button class="btn btn-warning">Joeys</button>
	<button class="btn btn-success">Cubs</button>
	<button class="btn btn-primary">Scouts</button>
	<button class="btn btn-primary">Venturers</button>
	<button class="btn btn-danger">Rovers</button>

</div>
<header>Let's Make a Camp Menu</header>

<nav class='nav'>
      <div class='cell'>
        <a class='nav-logo' href='/'>
          <div class='shing'>
            <img src='/assets/images/logo.png' alt='Sweet Lands' />
          </div>
        </a>
        <ul class='nav-menu'>
          <li><a href='#retweets'>Retweets</a></li>
          <li><a href='#pictures'>Pictures</a></li>
          <li><a href='#event'>Upcoming</a></li>
        </ul>
      </div>
    </nav>


<p> It is now <%= @time %><br/>
Customise Menu <%= link_to "Customise", generate_customise_path %>! 
</p>

CampfireButler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampfireButler</title>
  <!-- 
  	<%= stylesheet_link_tag	 "bootstrap.cerulean-theme" %>
  -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class ="container">
	<%= yield %>
</div>

</body>
</html>

CampfireButler/app/views/layouts/generate.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampfireButler</title>

  <%= stylesheet_link_tag	'generate', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class ="container">
	<%= yield %>
</div>

</body>
</html>

CampfireButler/app/views/meal_items/_form.html.erb
<%= form_for(@meal_item) do |f| %>
  <% if @meal_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_item.errors.count, "error") %> prohibited this meal_item from being saved:</h2>

      <ul>
      <% @meal_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : title %><br>
    <%= f.text_field : title %>
  </div>
  <div class="field">
    <%= f.label :num-serves %><br>
    <%= f.text_field :num-serves %>
  </div>
  <div class="field">
    <%= f.label :size-serve %><br>
    <%= f.text_field :size-serve %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CampfireButler/app/views/meal_items/edit.html.erb
<h1>Editing Meal Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal_item %> |
<%= link_to 'Back', meal_items_path %>

CampfireButler/app/views/meal_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meal Items</h1>

<table>
  <thead>
    <tr>
      <th> title</th>
      <th>Num-serves</th>
      <th>Size-serve</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_items.each do |meal_item| %>
      <tr>
        <td><%= meal_item. title %></td>
        <td><%= meal_item.num-serves %></td>
        <td><%= meal_item.size-serve %></td>
        <td><%= meal_item.comments %></td>
        <td><%= link_to 'Show', meal_item %></td>
        <td><%= link_to 'Edit', edit_meal_item_path(meal_item) %></td>
        <td><%= link_to 'Destroy', meal_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal item', new_meal_item_path %>

CampfireButler/app/views/meal_items/new.html.erb
<h1>New Meal Item</h1>

<%= render 'form' %>

<%= link_to 'Back', meal_items_path %>

CampfireButler/app/views/meal_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @meal_item. title %>
</p>

<p>
  <strong>Num-serves:</strong>
  <%= @meal_item.num-serves %>
</p>

<p>
  <strong>Size-serve:</strong>
  <%= @meal_item.size-serve %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @meal_item.comments %>
</p>

<%= link_to 'Edit', edit_meal_item_path(@meal_item) %> |
<%= link_to 'Back', meal_items_path %>